version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: vibe-coding-notes-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: vibe_coding_notes_dev
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d vibe_coding_notes_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: vibe-coding-notes-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: vibe-coding-notes-backend-dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/node_modules/.prisma
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://username:password@postgres:5432/vibe_coding_notes_dev
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev-jwt-secret-key
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=http://localhost:5173
      - SESSION_SECRET=dev-session-secret
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  # Frontend (Development - runs on host for hot reload)
  # Note: In development, frontend typically runs on host with `npm run dev`
  # This service is optional and can be used if containerized development is preferred
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: vibe-coding-notes-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  app-network:
    driver: bridge