version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vibe-coding-notes-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: vibe_coding_notes
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d vibe_coding_notes"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: vibe-coding-notes-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vibe-coding-notes-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/node_modules/.prisma
    environment:
      - DATABASE_URL=postgresql://username:password@vibe-coding-notes-db:5432/vibe_coding_notes
      - REDIS_URL=redis://vibe-coding-notes-redis:6379
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data: